---
services:
  autobrr:
    image: ghcr.io/unhelpful7417/autobrr-no-rars:main
    ports:
      - 7474:7474
    user: 1000:1000
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ./autobrr:/config
